filebeat.prospectors:
- paths:
   - /var/log/*.json
  input_type: log
  json.keys_under_root: true
  json.add_error_key: true

output.kafka:
  hosts: ["kafka:9092"]
  topic: 'filebeat'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
